# Use this template to audit a Gradle project for security vulnerabilities with JFrog Xray.
# The `jf audit` command works as follows:
#
# 1. It creates a depedency tree for the project, including the direct and indirect (transitives) depedencies
# 2. Scans the depedency tree with JFrog Xray
# 3. Dispayes the vulnerabilities found
#
# To creates the depedency tree, the command expects the depedecies to be present on the local agent.
# To ensure that, the `jf gradle artifactoryPublish` command is executed before the `jf audit` command.
#
# Requirements:
# Configure 'ARTIFACTORY_REPO' variable with the NuGet repository in JFrog Artifactorym
# from which the the depedencies can be resolved.

default:
  image: eclipse-temurin:11

jfrog-maven-build:
  script:
    # Configure JFrog Artifactory repositories
    - jf gradle-config --repo-resolve $ARTIFACTORY_REPO --use-wrapper

    # Ensure the project depedencies are present locally
    - jf gradle artifactoryPublish
    -
    # Audit Gradle project
    - jf audit
