# This template does the following:
#
# 1. Builds the project while resolving the dependencies from Artifactory
# 2. Uploads the build artifact to Artifactory
# 3. Publishes the build-info to Artifactory
#
# Requirements:
# Configure the following variables with the names of the  NuGet repositories in JFrog Artifactory:
#   'ARTIFACTORY_VIRTUAL_REPO', and 'ARTIFACTORY_LOCAL_REPO'.
default:
  image: mono

include:
  - remote: "https://releases.jfrog.io/artifactory/jfrog-cli/gitlab/.setup-jfrog.yml"
jfrog-nuget-build:
  script:
    - !reference [.setup_jfrog, script]

    # Configure JFrog Artifactory repositories
    - jf nuget-config --repo-resolve $ARTIFACTORY_VIRTUAL_REPO

    # Resolve dependencies from JFrog Artifactory
    - jf nuget restore

    # Upload artifact
    - jf rt u <path-to-local-file> <ARTIFACTORY_LOCAL_REPO>

    # Publish build-info to JFrog Artifactory
    - jf rt build-publish
